# Generated by Django 5.0.13 on 2025-05-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='weekdays',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
