# Generated by Django 5.0.13 on 2025-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
